### ISSUE TITLE
Check the issue

### ISSUE THREAD

**Issue by MariasStory** [hit-thusz-RookieCJ/FullSubNet-plus#4]
Dear author,
Thank you for this interesting solution.
Please check the comment from > PINTO0309 in:
https://github.com/PINTO0309/PINTO_model_zoo/issues/187

"The sound transformation model depends on the audio length, but how would you like the input width to be fixed? ONNX with a variable input width will cause an error in Reshape operation and cannot be used."

Additionally, PINTO0309 converted the model in different formats:
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/254_FullSubNet-plus

Thank you.

**Comment by hit-thusz-RookieCJ** [comment]
This model is capable of handling audio of different lengths when inference is made. It is possible to run without a fixed audio length.

**Comment by hit-thusz-RookieCJ** [comment]
About the queries in the link：

**Comment by hit-thusz-RookieCJ** [comment]
This model is capable of handling audio of different lengths when inference is made. It is possible to run without a fixed audio length.
About the queries in the link：
When the model is trained, a fixed length of audio is used within the batch, which is handled by the code itself. When the model is inference, since the batch_size is equal to 1, there is no need to worry about the audio length within the batch not being the same; while the audio length between different batches of the model does not need to be the same.
